name: Dogecoins
version: 1.0
description: Dogecoins plugin for DogeMC server

authors: [Chaten, CreeperzEdge, IncognitoJam]
website: https://www.reddit.com/r/dogecoin/

main: dogecoin.mc.dogecoins.Dogecoins
depend: [Vault]

commands:
  deposit:
    description: 'Deposit money through Dogecoin dogeAddress'
  money:
    description: 'List your in-game money balance'
  withdraw:
    description: 'Withdraw money to a Dogecoin dogeAddress'
  transact:
    description: 'Send in-game money to player'
  dogecoins:
    description: 'Print testing info'
  syscheck:
    description: 'Check Dogecoins system health'
  credit:
    description: 'Credit in-game money to player'
  debit:
    description: 'Debit in-game money from player'


permissions:
  dogecoins.admin:
    description: 'Permission for Dogecoins /satoshis'
  dogecoins.withdraw:
    description: 'Permission for Dogecoins /withdraw'
  dogecoins.deposit:
    description: 'Permission for Dogecoins /deposit'
  dogecoins.transact:
    description: 'Permission for Dogecoins /transact'
  dogecoins.money:
    description: 'Permission for Dogecoins /money'
  dogecoins.info:
    description: 'Permission for Dogecoins /syscheck'
  dogecoins.credit:
    description: 'Permission for Dogecoins /credit'
  dogecoins.debit:
    description: 'Permission for Dogecoins /debit'
