author: meta1203
database: true
main: me.meta1203.plugins.satoshis.Satoshis
name: Satoshis
startup: postworld
url: http://www.metaserve.net/
version: '0.1'
commands:
  deposit:
    description: 'Deposit money through Bitcoin address'
  money:
    description: 'List money in possession'
  withdraw:
    description: 'Withdraw money into Bitcoin address'
  transact:
    description: 'Send in-game money to player!'
  admin:
    description: 'Print testing info'
permissions:
  satoshis.admin:
    description: 'Permission for Satoshis /admin'
  satoshis.withdraw:
    description: 'Permission for Satoshis /withdraw'
  satoshis.deposit:
    description: 'Permission for Satoshis /deposit'
  satoshis.transact:
    description: 'Permission for Satoshis /transact'
  satoshis.money:
    description: 'Permission for Satoshis /money'
